# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3079b10e0c42ea142686720e1c38580efdd1fa0c236c9ee8add2e29858035bce4f608eaf56a7b369c50b3e2256fabfbd69f3801f5b0037e52bd0d10e0abf3d1

test:
  secret_key_base: ae5532b8680dd9f9bca2f61c681e65913ed0673ba26a971bb353087aa72a77d9274d2417b51bc51f7a76b891c9d6cff264116179b13e0843586297d9387e8d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
